---

- name: Create OpenMRS config directory
  ansible.builtin.file:
    group: "{{ deploy_group }}"
    owner: "{{ server_user }}"
    path: "/home/{{ server_user }}/.OpenMRS"
    state: directory
  become: yes
  become_user: "{{ server_user }}"
  tags: ["deploy", "emr", "kenya_emr"]

- name: Copy KenyaEMR 'omod' files to OpenMRS config dir
  ansible.builtin.copy:
    backup: no
    dest: "/home/{{ server_user }}/.OpenMRS"
    force: yes
    group: "{{ deploy_group }}"
    owner: "{{ server_user }}"
    remote_src: yes
    src: "/home/{{ server_user }}/{{ server_archive_name }}/modules"
  become: yes
  become_user: "{{ server_user }}"
  tags: ["deploy", "emr", "kenya_emr"]

- name: "Create datatool and etl databases"
  community.mysql.mysql_db:
    login_password: "{{ db_password }}"
    login_user: "{{ db_user }}"
    name: "{{ item }}"
    state: present
  loop:
    - kenyaemr_datatools
    - kenyaemr_etl
  tags: ["deploy", "emr", "kenya_emr"]

- name: Copy KenyaEMR and associated tools dbs dumps to remote machine
  ansible.builtin.copy:
    backup: no
    dest: "/tmp/kenyaemr_dbs.tar.xz"
    remote_src: no
    src: kenyaemr_dbs.tar.xz
  become: yes
  tags: ["deploy", "emr", "kenya_emr"]

- name: Unarchive the KenyaEMR and associated tools dbs dumps
  ansible.builtin.unarchive:
    dest: "/tmp"
    keep_newer: yes
    remote_src: yes
    src: /tmp/kenyaemr_dbs.tar.xz
  become: yes
  tags: ["deploy", "emr", "kenya_emr"]

- name: Restore KenyaEMR db dumps into associated prod dbs
  community.mysql.mysql_db:
    login_password: "{{ db_password }}"
    login_user: "{{ db_user }}"
    name: "{{ item.db_name }}"
    state: import
    target: "{{ item.db_dump_file }}"
  become: yes
  loop:
    - { db_dump_file: /tmp/kenyaemr_datatools.sql, db_name: kenyaemr_datatools }
    - { db_dump_file: /tmp/kenyaemr_etl.sql, db_name: kenyaemr_etl }
    - { db_dump_file: /tmp/openmrs.sql, db_name: openmrs }
  tags: ["deploy", "emr", "kenya_emr"]
